export const style = [
  {'featureType': 'administrative', 'elementType': 'labels.text.fill', 'stylers': [{'color': '#3c3c3c'}]},
  {'featureType': 'administrative.country', 'elementType': 'labels.text', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.country', 'elementType': 'labels.text.fill', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.country', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.province', 'elementType': 'geometry', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.province', 'elementType': 'labels.text.stroke', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.province', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.locality', 'elementType': 'labels.text', 'stylers': [{'visibility': 'simplified'}, {'saturation': '5'}, {'lightness': '-39'}, {'gamma': '2.50'}, {'weight': '0.01'}, {'hue': '#00ffd9'}]},
  {'featureType': 'administrative.neighborhood', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'administrative.land_parcel', 'elementType': 'geometry.fill', 'stylers': [{'saturation': '5'}]},
  {'featureType': 'administrative.land_parcel', 'elementType': 'labels.text.fill', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'administrative.land_parcel', 'elementType': 'labels.text.stroke', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'administrative.land_parcel', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'landscape', 'elementType': 'all', 'stylers': [{'color': '#f2f2f2'}, {'visibility': 'on'}]},
  {'featureType': 'landscape', 'elementType': 'geometry', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'landscape', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'landscape.man_made', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'on'}, {'saturation': '19'}]},
  {'featureType': 'poi', 'elementType': 'all', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'poi.attraction', 'elementType': 'labels.text', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'poi.attraction', 'elementType': 'labels.text.fill', 'stylers': [{'saturation': '-2'}]},
  {'featureType': 'poi.attraction', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'poi.business', 'elementType': 'geometry.fill', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'poi.business', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'poi.government', 'elementType': 'labels.text', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'poi.government', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'poi.park', 'elementType': 'geometry.fill', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'poi.park', 'elementType': 'labels.text', 'stylers': [{'visibility': 'on'}, {'saturation': '41'}, {'gamma': '1.09'}, {'lightness': '6'}]},
  {'featureType': 'poi.school', 'elementType': 'all', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'road', 'elementType': 'all', 'stylers': [{'saturation': '-100'}]},
  {'featureType': 'road.highway', 'elementType': 'geometry', 'stylers': [{'color': '#ffffff'}]},
  {'featureType': 'road.arterial', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'transit', 'elementType': 'labels.text.fill', 'stylers': [{'color': '#374757'}]},
  {'featureType': 'transit', 'elementType': 'labels.icon', 'stylers': [{'saturation': '-84'}]},
  {'featureType': 'transit.station.rail', 'elementType': 'labels.text.stroke', 'stylers': [{'visibility': 'off'}]},
  {'featureType': 'transit.station.rail', 'elementType': 'labels.icon', 'stylers': [{'visibility': 'on'}]},
  {'featureType': 'water', 'elementType': 'all', 'stylers': [{'color': '#d6ecff'}, {'visibility': 'on'}]},
  {'featureType': 'water', 'elementType': 'labels', 'stylers': [{'visibility': 'on'}, {'color': '#ffffff'}]}
]
